---
# Install OS specific beats

- name: Include specific Beats
  include: beats-debian.yml
  when: ansible_os_family == 'Debian'

- name: Include specific Beats
  include: beats-redhat.yml
  when: ansible_os_family == 'RedHat'

# Configuration file for beats
- name: Beats configuration
  include: beats-config.yml

# Create folder for spool file
- name: Create folder for spool file
  file:
    path: "{{ path_to_spool_file | regex_replace('spool.dat$', '') }}"
    state: directory
    owner: root
    group: root
    mode: '0700'
  become: yes
  when: use_spool_file

# Make sure the service is started, and restart if necessary
- name: Start beats service
  service:
    name: "{{ beat }}"
    state: started
    enabled: yes
  when: start_service | bool
  register: beats_started
